[versions]
agp = "8.9.1"
coreSdk = "3.8.3"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
library = "3.2.0-alpha11"
fastjson2 = "2.0.57.android8"
buildinfrastructure = "1.0.0-rc.1"
rxjava = "2.2.21"
loggingInterceptor = "5.0.0-alpha.14"
converterGson = "2.11.0"

[libraries]
core-sdk = { module = "io.openim:core-sdk", version.ref = "coreSdk" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
android-sdk = { group = "io.openim", name = "android-sdk", version = "3.8.3.2" }
library = { group = "androidx.databinding", name = "library", version.ref = "library" }
fastjson2 = { group = "com.alibaba.fastjson2", name = "fastjson2", version.ref = "fastjson2" }
buildinfrastructure = { group = "io.reactivex", name = "BuildInfrastructure", version.ref = "buildinfrastructure" }
rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
adapter-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version = "2.9.0" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

